### ISSUE TITLE
绘画生成的图片看不了

### ISSUE THREAD

**Issue by keethebest** [classfang/AIHub#3]
绘画生成的图片看不了，显示一个×，是需要设置代理吗？
<img width="693" alt="图片" src="https://github.com/classfang/AIHub/assets/5517347/00c237e5-4a4c-4ff0-8b63-200e376d5e46">

**Comment by classfang** [comment]
用的哪个模型？

**Comment by keethebest** [comment]
dall-e-3, mac客户端

**Comment by keethebest** [comment]
<img width="371" alt="图片" src="https://github.com/classfang/AIHub/assets/5517347/c348d0b4-9649-488d-855b-dc367619ef53">

**Comment by classfang** [comment]
可以在“设置”->"关于"->“打开开发者控制台”，看一下具体错误。

**Comment by keethebest** [comment]
<img width="1088" alt="图片" src="https://github.com/classfang/AIHub/assets/5517347/52e6aa07-ccb0-4d61-8267-28604ea1d938">
<img width="1053" alt="图片" src="https://github.com/classfang/AIHub/assets/5517347/114e7ee1-b3ed-4e12-8203-3e274a16d9e4">

接口访问成功了，本地的图片打不开

**Comment by keethebest** [comment]
试了3次，成功一次，失败2次

**Comment by keethebest** [comment]
[response.txt](https://github.com/classfang/AIHub/files/15037872/response.txt)
接口返回

**Comment by classfang** [comment]
已定位bug，保存base64数据时出现的错误，将在1.5.2版本修复。

**Comment by keethebest** [comment]
好的
