### ISSUE TITLE
是否支持调节字体大小？ 

### ISSUE THREAD

**Issue by 596192804** [classfang/AIHub#5]

**Comment by 596192804** [comment]
字体太小，看着有点难受，并且字体的段落行间距也有点窄了，如果可以的话，希望能够支持手动调节

**Comment by classfang** [comment]
方便附图标注一下，具体字体问题位置？

**Comment by 596192804** [comment]
补充一张chatgpt的效果：
![image](https://github.com/classfang/AIHub/assets/38677757/972f45bf-0c2f-4c3e-8fb2-8afea1b5da2e)

**Comment by classfang** [comment]
将在v1.8.6版本增加字体大小修改滑块，位置在 “设置->应用->外观” 中。

**Comment by 596192804** [comment]
好的，非常感谢！
